name: CI/CD Symfony

on:
  push:
    branches: [master]

jobs:

  build:
    name: 🔧 Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl, pdo_pgsql

      - name: Install Composer deps
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Lint YAML, Twig, PHP
        run: |
          php bin/console lint:yaml config
          php bin/console lint:twig templates
          php -l src

  test:
    name: ✅ Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run PHPUnit
        run: vendor/bin/phpunit --testdox

  deploy:
    name: 🚀 Deploy to Plesk
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H administratif.glessmer.fr >> ~/.ssh/known_hosts

      - name: Deploy files
        run: |
          rsync -az --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            ./ \
            glessmer@administratif.glessmer.fr:/var/www/vhosts/administratif.glessmer.fr/httpdocs

      - name: Post-deploy cache clear (optional)
        run: |
          ssh glessmer@administratif.glessmer.fr 'cd httpdocs && php bin/console cache:clear'
